name: 制作鹅鹅鹅系统
run-name: 制作鹅鹅鹅系统 ${{ inputs.target }}${{ inputs.fulldrv == true && ' - 完整驱动' || ' - 精简驱动' }}${{ inputs.latest == true && ' - 最新' || '' }}
on:
  workflow_dispatch:
    inputs:
      target:
        description: "目标系统版本"
        required: true
        type: choice
        options:
          - w1126h164
          - w1125h264
          - w1124h264
          - w1123h264
          - w1121h264
          - w1022h264
          - w11lt2464
          - w10lt2164
          - w10lt1964
          - w7ult64
      fulldrv:
        description: "添加完整驱动"
        required: false
        default: false
        type: boolean
      latest:
        description: "标记为最新版本"
        required: false
        default: false
        type: boolean

jobs:
  makexrsys:
    runs-on: windows-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v6

      - name: 获取 rclone 配置
        uses: actions/checkout@v6
        with:
          repository: yukaidi1220/rclone-action
          token: ${{ secrets.RCLONE_TOKEN }}
          path: bin

      - name: 执行构建任务
        shell: pwsh
        run: |
          # 安装 gsudo
          Invoke-WebRequest -Uri "https://github.com/gerardog/gsudo/releases/download/v2.6.1/gsudo.portable.zip" -OutFile "gsudo.zip"
          Expand-Archive -Path "gsudo.zip" -DestinationPath "gsudo"
          $env:Path = "$PWD\gsudo\x64;$env:Path"
          Import-Module "$PWD\gsudo\x64\gsudoModule.psm1"

          gsudo --ti .\makexrsys.ps1 -Target "${{ inputs.target }}" ${{ inputs.fulldrv == true && '-FullDrv' || '' }} ${{ inputs.latest == true && '-Latest' || '' }}
